### PR TITLE
Support specific namespaces

### LINKED ISSUE #7: Multiple database acting as source of entities
Define the modifications of the service to handle multiple databases where entities are stored.

The assumption is that different communities might use different databases to store their entities.

Onto-ns service could then explore and recover these entities and check if the uri exist in one or more of the database, if not return an error, if multiple but exactly equivalent return the entity (but inform the database managers about duplication) and if multiple different return error and inform databases managers.

### PR DESCRIPTION
**Pull request by CasperWA**
Closes #7 

Support multiple backends - to a degree - by having a separate backend for each specific namespace.
A specific namespace can be defined according to:

`<core namespace>/<specific namespace>/<entity version>/<entity name>`

Where the `/<specific namespace>` part is optional, and if given may contain forward slashes (`/`). It must not contain a dollar sign (`$`).

The Service has been updated accordingly to support uploading a collection of entities with differing namespaces (and therefore differing backends).

The CLI's upload command has been slightly updated as well to include a final confirmation prompt before uploading, which will show a table of the entities about to be uploaded according to the namespace, name and version of the entities.
Also, a JSON/YAML file with a list of entities is now supported by the upload command.

### CODE REVIEW

**Comment by francescalb** [comment]
I have so far only tested for uploading and it works nicely.

We do not have any restrictions on the /meta/ in the namespace, should we? (I think this is not something we need to decide here).

For the $ sign, the error message is difficult to understand, especially since it passes the first validation.

Could you add a clearer error message when there is an $ in the uri?

**Comment by CasperWA** [comment]
> I have so far only tested for uploading and it works nicely.

Note, it should be fine to go to the URL of the uploaded entities (locally), e.g., `http://localhost:8000/myNamespace/0.1/Person`, if you've uploaded such an entity :)

> We do not have any restrictions on the /meta/ in the namespace, should we? (I think this is not something we need to decide here).

It is by default in DLite part of the namespace. The full namespace hard-coded into DLite is: `http://onto-ns.com/meta`, this is also where this service is running in production.

> For the $ sign, the error message is difficult to understand, especially since it passes the first validation.
> 
> Could you add a clearer error message when there is an $ in the uri?

I'll take a look 👍

**Comment by francescalb** [comment]
> > I have so far only tested for uploading and it works nicely.
> 
> Note, it should be fine to go to the URL of the uploaded entities (locally), e.g., `http://localhost:8000/myNamespace/0.1/Person`, if you've uploaded such an entity :)
> 
Yes, that works. I intedned that I have not checked out other functionalities.

> > We do not have any restrictions on the /meta/ in the namespace, should we? (I think this is not something we need to decide here).
> 
> It is by default in DLite part of the namespace. The full namespace hard-coded into DLite is: `http://onto-ns.com/meta`, this is also where this service is running in production.
> 
Currently it accepts anything after http://localhost:8000/. There are no restrictions on the whether there should be a meta or where it should be in the namespace. Indeed, even this works: http://localhost:8000/0.1/Molecule (no namespace in additino to localhost.) Is this desired behaviour?


> > For the $ sign, the error message is difficult to understand, especially since it passes the first validation.
> > Could you add a clearer error message when there is an $ in the uri?
> 
> I'll take a look 👍

**Comment by CasperWA** [comment]
> > > We do not have any restrictions on the /meta/ in the namespace, should we? (I think this is not something we need to decide here).
> > 
> > 
> > It is by default in DLite part of the namespace. The full namespace hard-coded into DLite is: `http://onto-ns.com/meta`, this is also where this service is running in production.
> 
> Currently it accepts anything after http://localhost:8000/. There are no restrictions on the whether there should be a meta or where it should be in the namespace. Indeed, even this works: http://localhost:8000/0.1/Molecule (no namespace in additino to localhost.) Is this desired behaviour?

Ah, this is what you meant.

Yeah, for testing, this is fine.

The restriction throughout the system is that any URI provided here _must_ start with the base URL of the service, i.e., where it is running (this is set by the `ENTITIES_SERVICE_BASE_URL` environment variable). So using `http://localhost:8000` makes _this_ the value entities MUST start with. Under normal (i.e., in production) circumstances this value is `http://onto-ns.com/meta`.

**Comment by francescalb** [comment]
> > > > We do not have any restrictions on the /meta/ in the namespace, should we? (I think this is not something we need to decide here).
> > > 
> > > 
> > > It is by default in DLite part of the namespace. The full namespace hard-coded into DLite is: `http://onto-ns.com/meta`, this is also where this service is running in production.
> > 
> > 
> > Currently it accepts anything after http://localhost:8000/. There are no restrictions on the whether there should be a meta or where it should be in the namespace. Indeed, even this works: http://localhost:8000/0.1/Molecule (no namespace in additino to localhost.) Is this desired behaviour?
> 
> Ah, this is what you meant.
> 
> Yeah, for testing, this is fine.
> 
> The restriction throughout the system is that any URI provided here _must_ start with the base URL of the service, i.e., where it is running (this is set by the `ENTITIES_SERVICE_BASE_URL` environment variable). So using `http://localhost:8000` makes _this_ the value entities MUST start with. Under normal (i.e., in production) circumstances this value is `http://onto-ns.com/meta`.

Thanx for the calrification. That makes sense.

**Review by francescalb — CHANGES_REQUESTED** [review]
Almost approved from my side. I have tested various combinations in the uris when uploading to a local database, and it worked nicely. 

I aonly would like to have a better error reported when including a $ in the uri, as this is not accepted, but the error message does not reflect that this is the problem.

**Review by francescalb — APPROVED** [review]
Worked for me locally :)

**Pull request merged**
